swagger: '2.0'

################################################################################
#                               API Information                                #
################################################################################
info:
  title: OpsGenie REST API
  description: OpsGenie RESTful API specifications
  version: "2.0.0"
# the domain of the service
host: api.opsgenie.com
# array of all schemes that your API supports
schemes:
  - https
# format of the responses to the client (Accepts)
produces:
  - application/json

################################################################################
#                                  Security                                    #
################################################################################
securityDefinitions:
  GenieKey:
    type: apiKey
    name: Authorization
    in: header
security:
  - GenieKey: []

################################################################################
#                                    PATHS                                     #
################################################################################
paths:
  - $ref: ./paths/alert.yaml
  - $ref: ./paths/integration.yaml  # Will be implemented
  - $ref: ./paths/heartbeat.yaml
  - $ref: ./paths/policy.yaml # Will be implemented
  - $ref: ./paths/maintenance.yaml
  - $ref: ./paths/account.yaml
  - $ref: ./paths/user.yaml
  - $ref: ./paths/contact.yaml
  - $ref: ./paths/notificationRule.yaml # Will be implemented
  - $ref: ./paths/notificationRuleStep.yaml
  - $ref: ./paths/team.yaml
  - $ref: ./paths/teamMember.yaml
  - $ref: ./paths/teamRoutingRule.yaml  # Will be implemented
  - $ref: ./paths/schedule.yaml
  - $ref: ./paths/scheduleRotation.yaml
  - $ref: ./paths/scheduleOverride.yaml # Will be implemented
  - $ref: ./paths/whoIsOnCall.yaml  # Will be implemented
  - $ref: ./paths/escalation.yaml
  - $ref: ./paths/forwardingRule.yaml

################################################################################
#                                  PARAMETERS                                  #
################################################################################
parameters:
  - $ref: ./parameters/common.yaml
  - $ref: ./parameters/alert.yaml
  - $ref: ./parameters/integration.yaml  # Will be implemented
  - $ref: ./parameters/heartbeat.yaml
  - $ref: ./parameters/policy.yaml # Will be implemented
  - $ref: ./parameters/maintenance.yaml
  - $ref: ./parameters/user.yaml
  - $ref: ./parameters/contact.yaml
  - $ref: ./parameters/notificationRule.yaml # Will be implemented
  - $ref: ./parameters/notificationRuleStep.yaml
  - $ref: ./parameters/team.yaml
  - $ref: ./parameters/teamMember.yaml
  - $ref: ./parameters/teamRoutingRule.yaml  # Will be implemented
  - $ref: ./parameters/schedule.yaml
  - $ref: ./parameters/scheduleRotation.yaml # Will be implemented
  - $ref: ./parameters/scheduleOverride.yaml # Will be implemented
  - $ref: ./parameters/whoIsOnCall.yaml  # Will be implemented
  - $ref: ./parameters/escalation.yaml
  - $ref: ./parameters/forwardingRule.yaml

################################################################################
#                                 RESPONSES                                    #
################################################################################
responses:
  - $ref: ./responses/common.yaml
  - $ref: ./responses/integration.yaml  # Will be implemented
  - $ref: ./responses/policy.yaml # Will be implemented
  - $ref: ./responses/notificationRule.yaml # Will be implemented

  - $ref: ./responses/teamRoutingRule.yaml  # Will be implemented
  - $ref: ./responses/whoIsOnCall.yaml  # Will be implemented

################################################################################
#                                DEFINITIONS                                   #
################################################################################
definitions:
  - $ref: ./definitions/common.yaml
  - $ref: ./definitions/alert.yaml
  - $ref: ./definitions/integration.yaml  # Will be implemented
  - $ref: ./definitions/heartbeat.yaml
  - $ref: ./definitions/policy.yaml # Will be implemented
  - $ref: ./definitions/maintenance.yaml
  - $ref: ./definitions/account.yaml
  - $ref: ./definitions/user.yaml
  - $ref: ./definitions/contact.yaml
  - $ref: ./definitions/notificationRule.yaml # Will be implemented
  - $ref: ./definitions/notificationRuleStep.yaml
  - $ref: ./definitions/team.yaml
  - $ref: ./definitions/teamMember.yaml
  - $ref: ./definitions/teamRoutingRule.yaml  # Will be implemented
  - $ref: ./definitions/schedule.yaml
  - $ref: ./definitions/scheduleRotation.yaml
  - $ref: ./definitions/scheduleOverride.yaml # Will be implemented
  - $ref: ./definitions/whoIsOnCall.yaml  # Will be implemented
  - $ref: ./definitions/escalation.yaml
  - $ref: ./definitions/forwardingRule.yaml
